# GApps dependencies
PRODUCT_COPY_FILES += \
	vendor/google/mako/proprietary/system/system/lib/librs.antblur_drama.so:system/lib/librs.antblur_drama \
	vendor/google/mako/proprietary/system/system/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so \
	vendor/google/mako/proprietary/system/system/lib/librs.image_wrapper.so:system/lib/librs.image_wrapper.so \
	vendor/google/mako/proprietary/system/system/lib/libgames_rtmp_jni.so:system/lib/libgames_rtmp_jni.so \
	vendor/google/mako/proprietary/system/system/lib/libwebrtc_audio_preprocessing.so:system/lib/libwebrtc_audio_preprocessing.so \
	vendor/google/mako/proprietary/system/system/lib/librs.film_base.so:system/lib/librs.film_base.so \
	vendor/google/mako/proprietary/system/system/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so \
	vendor/google/mako/proprietary/system/system/lib/libfrsdk.so:system/lib/libfrsdk.so \
	vendor/google/mako/proprietary/system/system/lib/libwebp_android.so:system/lib/libwebp_android.so \
	vendor/google/mako/proprietary/system/system/lib/librs.antblur.so:system/lib/librs.antblur.so \
	vendor/google/mako/proprietary/system/system/lib/libRSSupport.so:system/lib/libRSSupport.so \
	vendor/google/mako/proprietary/system/system/lib/libplus_jni_v8.so:system/lib/libplus_jni_v8.so \
	vendor/google/mako/proprietary/system/system/lib/libfilterframework_jni.so:system/lib/libfilterframework_jni.so \
	vendor/google/mako/proprietary/system/system/lib/librs.drama.so:system/lib/librs.drama.so \
	vendor/google/mako/proprietary/system/system/lib/librs.grey.so:system/lib/librs.grey.so \
	vendor/google/mako/proprietary/system/system/lib/librs.retrolux.so:system/lib/librs.retrolux.so \
	vendor/google/mako/proprietary/system/system/lib/libAppDataSearch.so:system/lib/libAppDataSearch.so \
	vendor/google/mako/proprietary/system/system/lib/libmoviemaker-jni.so:system/lib/libmoviemaker-jni.so \
	vendor/google/mako/proprietary/system/system/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
	vendor/google/mako/proprietary/system/system/lib/libgoogle_recognizer_jni_l.so:system/lib/libgoogle_recognizer_jni_l.so \
	vendor/google/mako/proprietary/system/system/lib/librsjni.so:system/lib/librsjni.so \
	vendor/google/mako/proprietary/system/system/lib/libfacetracker.so:system/lib/libfacetracker.so \
	vendor/google/mako/proprietary/system/system/lib/librs.fixedframe.so:system/lib/librs.fixedframe.so \
	vendor/google/mako/proprietary/system/system/lib/librs.antblur_constant.so:system/lib/librs.antblur_constant.so \
	vendor/google/mako/proprietary/system/system/lib/libnetjni.so:system/lib/libnetjni.so \
	vendor/google/mako/proprietary/system/system/lib/libwebrtc_audio_coding.so:system/lib/libwebrtc_audio_coding.so \
	vendor/google/mako/proprietary/system/system/lib/libvideochat_jni.so:system/lib/libvideochat_jni.so \
	vendor/google/mako/proprietary/system/system/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
	vendor/google/mako/proprietary/system/system/lib/libstlport_shared.so:system/lib/libstlport_shared.so \
	vendor/google/mako/proprietary/system/system/lib/libjni_t13n_shared_engine.so:system/lib/libjni_t13n_shared_engine.so \
	vendor/google/mako/proprietary/system/system/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
	vendor/google/mako/proprietary/system/system/lib/libdocscanner_image-v7a.so:system/lib/libdocscanner_image-v7a.so \
	vendor/google/mako/proprietary/system/system/lib/libdocsimageutils.so:system/lib/libdocsimageutils.so \
	vendor/google/mako/proprietary/system/system/lib/libearthandroid.so:system/lib/libearthandroid.so \
	vendor/google/mako/proprietary/system/system/lib/libearthmobile.so:system/lib/libearthmobile.so \
	vendor/google/mako/proprietary/system/system/lib/libjni_latinime.so:system/lib/libjni_latinime.so \
	vendor/google/mako/proprietary/system/system/lib/libjni_latinimegoogle.so:system/lib/libjni_latinimegoogle.so \
	vendor/google/mako/proprietary/system/system/lib/liblinearalloc.so:system/lib/liblinearalloc.so \
	vendor/google/mako/proprietary/system/system/lib/libndk1.so:system/lib/libndk1.so \
	vendor/google/mako/proprietary/system/system/lib/libocrclient.so.so:system/lib/libocrclient.so \
	vendor/google/mako/proprietary/system/system/lib/librectifier-v7a.so:system/lib/librectifier-v7a.so \
	vendor/google/mako/proprietary/system/system/lib/libvorbisencoder.so:system/lib/libvorbisencoder.so\	
	vendor/google/mako/proprietary/system/system/addon.d/70-gapps.sh:system/addon.d/70-gapps.sh \
	vendor/google/mako/proprietary/system/system/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar \
	vendor/google/mako/proprietary/system/system/framework/com.google.widevine.software.drm.jar:system/framework/com.google.widevine.software.drm.jar \
	vendor/google/mako/proprietary/system/system/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar \
	vendor/google/mako/proprietary/system/system/etc/permissions/features.xml:system/etc/permissions/features.xml \
	vendor/google/mako/proprietary/system/system/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
	vendor/google/mako/proprietary/system/system/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml \
	vendor/google/mako/proprietary/system/system/etc/permissions/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml \
	vendor/google/mako/proprietary/system/system/etc/preferred-apps/google.xml:system/etc/preferred-apps/google.xml \
	vendor/google/mako/proprietary/system/system/etc/g.prop:system/etc/g.prop \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/dict:system/usr/srec/en-US/dict \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/hmmlist:system/usr/srec/en-US/hmmlist \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/hotword_word_symbols:system/usr/srec/en-US/hotword_word_symbols \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/dnn:system/usr/srec/en-US/dnn \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/ep_acoustic_model:system/usr/srec/en-US/ep_acoustic_model \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/hotword_classifier:system/usr/srec/en-US/hotword_classifier \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/hotword_normalizer:system/usr/srec/en-US/hotword_normalizer \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/wordlist:system/usr/srec/en-US/wordlist \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/commands.abnf:system/usr/srec/en-US/commands.abnf \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/normalizer:system/usr/srec/en-US/normalizer \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/offensive_word_normalizer:system/usr/srec/en-US/offensive_word_normalizer \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/clg:system/usr/srec/en-US/clg \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/rescoring_lm:system/usr/srec/en-US/rescoring_lm \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/hmm_symbols:system/usr/srec/en-US/hmm_symbols \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/phone_state_map:system/usr/srec/en-US/phone_state_map \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/hotword.config:system/usr/srec/en-US/hotword.config \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/hclg_shotword:system/usr/srec/en-US/hclg_shotword \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/hotword_prompt.txt:system/usr/srec/en-US/hotword_prompt.txt \
	vendor/google/mako/proprietary/system/system/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst

PRODUCT_PACKAGES += \
	MediaUploader /
	GoogleTTS /
	GenieWidget /
	PlusOne /
	GoogleHome /
	GoogleContactsSyncAdapter /
	YouTube /
	Maps /
	ChromeBookmarksSyncAdapter /
	Gmail2 /
	Street /
	CalendarGoogle /
	Hangouts /
	SetupWizard /
	Velvet /
	Phonesky /
	GooglePartnerSetup /
	GoogleBackupTransport /
	GoogleServicesFramework /
	PrebuiltGmsCore /
	GoogleFeedback /
	GoogleLoginService /
	CalendarProvider /
	OneTimeInitializer /

# FaceLock build.prop
PRODUCT_PROPERTY_OVERRIDES += \
    ro.facelock.black_timeout=1250 \
    ro.facelock.det_timeout=1500 \
    ro.facelock.rec_timeout=2500 \
    ro.facelock.lively_timeout=2500 \
    ro.facelock.est_max_time=1000 \
    ro.facelock.use_intro_anim=true
